services:
  postgres:
    image: postgres:17
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  frontend:
    build: C:/Users/kisho/Projects/vbr_office_frontend/vbr_office_frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  pgdata:
