sonar.projectKey=vbr_office_backend
sonar.projectName=VBR Office Backend
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.host.url=http://localhost:9000
sonar.token=squ_993ddde7bcd8dba0b8ba7f28dd4f802c69353fcd
